#
# This Docker Compose recipe is meant for spinning up the
# accompanying data services required to perform development
# and engineering work against SHIELD Storage Gateway software.
#
# It is not meant to be used directly in production, although
# it does act as a decent template for what we will need
# when we do finally launch.
#
# Note that there are no volumes in this recipe.
# Data will not persist across container restarts.
# This is a feature of the test environment, not a bug.
#
# You should never have to run this recipe by hand -- the
# integration test suite handles it for you. However, if you
# need (or want) to:
#
#     PUBLIC_PORT=9077 \
#       docker-compose -p ssg-it -f t/docker-compose.yml up
#

version: '2'
services:
  vault:
    build:
      context: aux
      dockerfile: Dockerfile.vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=ichaeZeeth5ichi1OhxooSahpoo8wa
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_API_ADDR=http://vault:8200
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=ichaeZeeth5ichi1OhxooSahpoo8wa
    command:
      - vault
      - server
      - -dev

  gateway:
    depends_on:
      - vault
    build: &build
      context: ..
      #args:
      #  VERSION: 0.0.0
    ports: ["$PUBLIC_PORT:8080"]
    environment:
      - SSG_LOG_LEVEL=debug
      - SSG_CONFIG=/etc/ssg/ssg.yml
    volumes:
      - $PWD/t/ssg.yml:/etc/ssg/ssg.yml
      - $PWD/t/tmp:/srv/files
