#!/bin/sh
set -e

exec 1>&2
echo

export PUBLIC_PORT=${PUBLIC_PORT:-9077}
if [[ -z "${SSG_NO_BUILD:-}" ]]; then
  echo "» building SSG API OCI image…"
  docker-compose -p ssg_integration_tests -f t/docker-compose.yml build
fi
rm -rf t/tmp/*
echo "» (re)starting INTEGRATION TEST docker compose infrastructure…"
docker-compose -p ssg_integration_tests -f t/docker-compose.yml down -v
docker-compose -p ssg_integration_tests -f t/docker-compose.yml up -d
echo "» waiting for vault to come online…"
n=300
while [[ $n != 0 ]]; do
  if docker exec -e VAULT_ADDR=http://127.0.0.1:8200 ssg_integration_tests_vault_1 vault status >/dev/null 2>&1; then
    echo "» waiting for http://127.0.0.1:$PUBLIC_PORT/ to come online…"
    n=300
    while [[ $n != 0 ]]; do
      if curl --connect-timeout 1 -sf http://127.0.0.1:$PUBLIC_PORT/ >/dev/null; then
        echo "» generating pbkdf2 fixed key at secret/tests/fixed…"
        docker exec ssg_integration_tests_vault_1 vault kv put secret/tests/fixed key=`dd 2>/dev/null if=/dev/urandom bs=64 count=1 | xxd -ps -c 200 | tr -d '\n'`
        exit 0
      fi
      sleep 0.1
      n=$((n - 1))
    done
    exit 1
  fi
  sleep 0.1
  n=$((n - 1))
done
exit 1
